version: "2"
services:
  japan-cinema-status-rest-api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes: 
      - .:/app
    ports: 
      - "8080:8080"
    working_dir: /app
    networks:
      - japancinemastatusspider_default
networks:
  japancinemastatusspider_default:
    external: true